site_name: SimpleNDArray
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            filters:
              - "!^__all__$"
