# Auto-generated stub for compiled functions.
from __future__ import annotations
from typing import TYPE_CHECKING
from typing import Callable, ClassVar

from simplendarray.transpiler.runtime import PythonModule

class _ReductionModuleClass(PythonModule):
    if TYPE_CHECKING:
        DISPATCH_DICT_reduction: ClassVar[dict[tuple, Callable[..., None]]]

        def reduction_add_float(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_float(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_float(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_double(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_double(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_double(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_unsigned_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_unsigned_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_unsigned_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_char(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_unsigned_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_unsigned_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_unsigned_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_short(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_unsigned_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_unsigned_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_unsigned_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_int(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_unsigned_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_unsigned_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_unsigned_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_add_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_max_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        def reduction_min_long_long(self, a: int, a_off: int, a_row_stride: int, a_col_stride: int, c: int, c_off: int, c_stride: int, n: int, d: int) -> None: ...
        pass
