# Auto-generated stub for compiled functions.
from __future__ import annotations
from typing import TYPE_CHECKING
from typing import Callable, ClassVar

from simplendarray.transpiler.runtime import PythonModule

class _ElementWiseModuleClass(PythonModule):
    if TYPE_CHECKING:
        DISPATCH_DICT_element_wise_binary: ClassVar[dict[tuple, Callable[..., None]]]
        DISPATCH_DICT_element_wise_unary: ClassVar[dict[tuple, Callable[..., None]]]
        DISPATCH_DICT_arange: ClassVar[dict[tuple, Callable[..., None]]]
        DISPATCH_DICT_reshape_copy: ClassVar[dict[tuple, Callable[..., None]]]

        def element_wise_binary_float__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_float__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_float__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_float__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_float__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_double__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_double__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_double__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_double__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_double__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_char__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_char__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_char__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_char__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_char__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_char__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_char__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_char__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_char__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_char__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_short__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_short__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_short__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_short__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_short__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_short__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_short__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_short__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_short__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_short__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_int__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_int__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_int__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_int__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_int__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_int__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_int__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_int__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_int__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_int__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_long_long__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_long_long__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_long_long__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_long_long__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_unsigned_long_long__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_long_long__add(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_long_long__sub(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_long_long__mul(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_long_long__div(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_binary_long_long__atan2(self, a: int, a_off: int, a_stride: int, b: int, b_off: int, b_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_float__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_double__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_char__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_char__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_short__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_short__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_int__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_int__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_unsigned_long_long__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__exp(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__exp2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__log(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__log2(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__log10(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__relu(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__square(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__sqrt(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__sin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__cos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__tan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__asin(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__acos(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__atan(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__sinh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__cosh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def element_wise_unary_long_long__tanh(self, a: int, a_off: int, a_stride: int, c: int, c_off: int, c_stride: int, n: int) -> None: ...
        def arange_float(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_double(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_unsigned_char(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_char(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_unsigned_short(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_short(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_unsigned_int(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_int(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_unsigned_long_long(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def arange_long_long(self, out: int, out_offset: int, out_stride: int, numel: int) -> None: ...
        def reshape_copy_float(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_double(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_unsigned_char(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_char(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_unsigned_short(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_short(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_unsigned_int(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_int(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_unsigned_long_long(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        def reshape_copy_long_long(self, inp: int, inp_strides: int, inp_shape: int, inp_index: int, inp_offset: int, inp_ndim: int, out: int, out_strides: int, out_shape: int, out_index: int, out_offset: int, out_ndim: int, numel: int) -> None: ...
        pass
